# Generated by Django 6.0.6 on 2026-06-09 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("promotion_date", models.DateField(default="2025-01-01")),
                ("academy", models.CharField(blank=True, max_length=300, null=True)),
                ("notes", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "actual_belt",
                    models.CharField(
                        choices=[
                            ("WHITE", "Public"),
                            ("YELLOW", "Yellow"),
                            ("ORANGE", "Orange"),
                            ("BLUE", "Blue"),
                            ("PURPLE", "Purple"),
                            ("BROWN", "Brown"),
                            ("Black", "Black"),
                        ],
                        default="WHITE",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belt_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
