# Generated by Django 5.2.8 on 2025-11-29 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_belt",
                    models.CharField(
                        choices=[
                            ("WHITE", "Public"),
                            ("YELLOW", "Yellow"),
                            ("ORANGE", "Orange"),
                            ("BLUE", "Blue"),
                            ("PURPLE", "Purple"),
                            ("BROWN", "Brown"),
                            ("Black", "Black"),
                        ],
                        default="WHITE",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
