# Generated by Django 5.2.8 on 2025-12-21 18:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bjjapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beltpromotion",
            name="academy",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="beltpromotion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beltpromotion",
            name="notes",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="beltpromotion",
            name="promotion_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="beltpromotion",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beltpromotion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
