# Generated by Django 5.2.8 on 2026-01-04 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bjjapp", "0002_beltpromotion_academy_beltpromotion_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltpromotion",
            name="promotion_date",
            field=models.DateField(default="2025-01-01"),
        ),
        migrations.AlterField(
            model_name="beltpromotion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="belt_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
