# Generated by Django 5.2.8 on 2025-11-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pseudo",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
