# Generated by Django 5.2.8 on 2026-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pseudo_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
