# Generated by Django 6.0.6 on 2026-06-09 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("QUADS", "Quads"),
                            ("ISCHIOS", "Ischios"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("SHOULDERS", "Shoulders"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("LOWER_BACK", "Lower Back"),
                            ("LATS", "Lats"),
                            ("UPPER_BACK", "Upper Back"),
                            ("REAR_SHOULDERS", "Rear Shoulders"),
                            ("CORE", "Core"),
                            ("FULL_BODY", "Full Body"),
                            ("FOREARMS", "Forearms"),
                        ],
                        max_length=20,
                    ),
                ),
                ("equipment_needed", models.CharField(blank=True, max_length=100)),
                ("is_compound", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                (
                    "secondary_muscle_groups",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("QUADS", "Quads"),
                            ("ISCHIOS", "Ischios"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("SHOULDERS", "Shoulders"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("LOWER_BACK", "Lower Back"),
                            ("LATS", "Lats"),
                            ("UPPER_BACK", "Upper Back"),
                            ("REAR_SHOULDERS", "Rear Shoulders"),
                            ("CORE", "Core"),
                            ("FULL_BODY", "Full Body"),
                            ("FOREARMS", "Forearms"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Strength"),
                            ("HYPERTROPHY", "Hypertrophy"),
                            ("ENDURANCE", "Endurance"),
                            ("FULL_BODY", "Full Body"),
                            ("CROSSFIT", "Crossfit"),
                            ("FITNESS", "Fitness"),
                            ("PUSH_PULL_LEGS", "Push/Pull/Legs"),
                            ("SPLIT", "Split"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("set_number", models.IntegerField()),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reps", models.IntegerField()),
                ("rpe", models.IntegerField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("rest_seconds", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_warmup", models.BooleanField(default=False)),
                ("is_failure", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="liftapp.exercise",
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="liftapp.workoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Strength"),
                            ("HYPERTROPHY", "Hypertrophy"),
                            ("ENDURANCE", "Endurance"),
                            ("FULL_BODY", "Full Body"),
                            ("CROSSFIT", "Crossfit"),
                            ("FITNESS", "Fitness"),
                            ("PUSH_PULL_LEGS", "Push/Pull/Legs"),
                            ("SPLIT", "Split"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_duration", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="liftapp.workouttemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                ("target_sets", models.IntegerField(default=3)),
                ("target_reps_min", models.IntegerField(blank=True, null=True)),
                ("target_reps_max", models.IntegerField(blank=True, null=True)),
                ("rest_seconds", models.IntegerField(default=90)),
                ("notes", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liftapp.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="liftapp.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "order")},
            },
        ),
    ]
