# Generated by Django 5.2.8 on 2026-01-04 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("QUADS", "Quads"),
                            ("ISCHIOS", "Ischios"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("SHOULDERS", "Shoulders"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("LOWER_BACK", "Lower Back"),
                            ("LATS", "Lats"),
                            ("UPPER_BACK", "Upper Back"),
                            ("REAR_SHOULDERS", "Rear Shoulders"),
                            ("CORE", "Core"),
                            ("FULL_BODY", "Full Body"),
                            ("FOREARMS", "Forearms"),
                        ],
                        max_length=20,
                    ),
                ),
                ("equipment_needed", models.CharField(blank=True, max_length=100)),
                ("is_compound", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Strength"),
                            ("HYPERTROPHY", "Hypertrophy"),
                            ("ENDURANCE", "Endurance"),
                            ("FULL_BODY", "Full Body"),
                            ("CROSSFIT", "Crossfit"),
                            ("FITNESS", "Fitness"),
                            ("PUSH_PULL_LEGS", "Push/Pull/Legs"),
                            ("SPLIT", "Split"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_duration", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                ("target_sets", models.IntegerField(default=3)),
                ("target_reps_min", models.IntegerField(blank=True, null=True)),
                ("target_reps_max", models.IntegerField(blank=True, null=True)),
                ("rest_seconds", models.IntegerField(default=90)),
                ("notes", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liftapp.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercices",
                        to="liftapp.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "order")},
            },
        ),
    ]
