# Generated by Django 5.2.8 on 2026-07-01 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liftapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("QUADS", "Quads"),
                            ("ISCHIOS", "Ischios"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("SHOULDERS", "Shoulders"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("LOWER_BACK", "Lower Back"),
                            ("LATS", "Lats"),
                            ("UPPER_BACK", "Upper Back"),
                            ("REAR_SHOULDERS", "Rear Shoulders"),
                            ("CORE", "Core"),
                            ("FULL_BODY", "Full Body"),
                            ("FOREARMS", "Forearms"),
                        ],
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEIGHT_REPS", "Weight & Reps"),
                    ("REPS_ONLY", "Reps Only"),
                    ("DURATION", "Duration"),
                    ("DISTANCE_DURATION", "Distance & Duration"),
                    ("BODYWEIGHT_WEIGHTED", "Bodyweight lesté"),
                    ("BODYWEIGHT_ASSISTED", "Bodyweight assisté"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="secondary_muscle_groups",
        ),
        migrations.CreateModel(
            name="ProgramType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRENGTH", "Strength"),
                            ("HYPERTROPHY", "Hypertrophy"),
                            ("ENDURANCE", "Endurance"),
                            ("FULL_BODY", "Full Body"),
                            ("CROSSFIT", "Crossfit"),
                            ("FITNESS", "Fitness"),
                            ("PUSH_PULL_LEGS", "Push/Pull/Legs"),
                            ("SPLIT", "Split"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "templates",
                    models.ManyToManyField(blank=True, to="liftapp.workouttemplate"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="secondary_muscle_groups",
            field=models.ManyToManyField(blank=True, to="liftapp.musclegroup"),
        ),
    ]
