# Generated by Django 5.2.8 on 2026-07-01 13:34

from django.db import migrations

def populate_muscle_groups(apps, schema_editor):
    MuscleGroup = apps.get_model('liftapp', 'MuscleGroup')
    muscle_list = ['CHEST', 'BACK', 'QUADS', 'ISCHIOS', 'GLUTES', 
                   'CALVES', 'SHOULDERS', 'BICEPS', 'TRICEPS', 
                   'LOWER_BACK', 
                   'LATS', 'UPPER_BACK', 'REAR_SHOULDERS', 
                   'CORE', 'FULL_BODY', 'FOREARMS']
    
    for detail in muscle_list: 
        MuscleGroup.objects.get_or_create(name=detail)
        
def delete_muscle_groups(apps, schema_editor):
    MuscleGroup = apps.get_model('liftapp', 'MuscleGroup')
    MuscleGroup.objects.all().delete()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ("liftapp", "0002_musclegroup_alter_exercise_exercise_type_and_more"),
    ]

    operations = [migrations.RunPython(populate_muscle_groups, delete_muscle_groups)]
