# Generated by Django 5.2.8 on 2026-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liftapp", "0003_auto_20260701_1534"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("CHEST", "Chest"),
                    ("BACK", "Back"),
                    ("QUADS", "Quads"),
                    ("ISCHIOS", "Ischios"),
                    ("GLUTES", "Glutes"),
                    ("CALVES", "Calves"),
                    ("SHOULDERS", "Shoulders"),
                    ("BICEPS", "Biceps"),
                    ("TRICEPS", "Triceps"),
                    ("LOWER_BACK", "Lower Back"),
                    ("LATS", "Lats"),
                    ("UPPER_BACK", "Upper Back"),
                    ("REAR_SHOULDERS", "Rear Shoulders"),
                    ("CORE", "Core"),
                    ("FULL_BODY", "Full Body"),
                    ("FOREARMS", "Forearms"),
                    ("ADDUCTORS", "Adductors"),
                    ("ABDUCTORS", "Abductors"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="musclegroup",
            name="name",
            field=models.CharField(
                choices=[
                    ("CHEST", "Chest"),
                    ("BACK", "Back"),
                    ("QUADS", "Quads"),
                    ("ISCHIOS", "Ischios"),
                    ("GLUTES", "Glutes"),
                    ("CALVES", "Calves"),
                    ("SHOULDERS", "Shoulders"),
                    ("BICEPS", "Biceps"),
                    ("TRICEPS", "Triceps"),
                    ("LOWER_BACK", "Lower Back"),
                    ("LATS", "Lats"),
                    ("UPPER_BACK", "Upper Back"),
                    ("REAR_SHOULDERS", "Rear Shoulders"),
                    ("CORE", "Core"),
                    ("FULL_BODY", "Full Body"),
                    ("FOREARMS", "Forearms"),
                    ("ADDUCTORS", "Adductors"),
                    ("ABDUCTORS", "Abductors"),
                ],
                max_length=200,
                unique=True,
            ),
        ),
    ]
