# Generated by Django 5.2.8 on 2026-07-28 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liftapp", "0004_alter_exercise_muscle_group_alter_musclegroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsession",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
