# Generated by Django 5.2.8 on 2026-08-04 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liftapp", "0005_alter_workoutsession_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="reps",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
